apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cryptodata
  namespace: logaiter
spec:
  resources:
    requests:
      storage: 1Gi
  volumeMode: Filesystem
  # storageClassName: standard              # minikube
  storageClassName: local-path           # rancher-desktop
  accessModes:
    - ReadWriteOnce
