apiVersion: v1
kind: Pod
metadata:
  namespace: logaiter
  name: test-lg
  labels:
    app.kubernetes.io/managed-by: logaiter
spec:
  containers:
  - name: test
    image: nginx
    resources:
      requests:
        memory: "32Mi"
        cpu: "5m"
      limits:
        memory: "64Mi"
        cpu: "10m"
    ports:
      - containerPort: 80
  nodeSelector:
    logaiter/node-enabled: "true"