apiVersion: v1
kind: Pod
metadata:
  name: apiv1
  namespace: gag
  labels:
    app.kubernetes.io/part-of: gag-cs
    app.kubernetes.io/component: api    
spec:
  hostname: api-v1
  subdomain: vexapi
  containers:
  - name: vexamen
    image: quay.io/k8sexercices/vexamen-server:v1.0
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
    - containerPort: 8080
      name: http
---
apiVersion: v1
kind: Pod
metadata:
  name: apiv2
  namespace: gag
  labels:
    app.kubernetes.io/part-of: gag-cs
    app.kubernetes.io/component: api    
spec:
  hostname: api-v2
  subdomain: vexapi
  containers:
  - name: vexamen
    image: quay.io/k8sexercices/vexamen-server:v2.0
    resources:
      limits:
        memory: "64Mi"
        cpu: "50m"
    ports:
    - containerPort: 8080
      name: http
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gag
  name: clientv1
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gag-cs
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: gag-cs
        app.kubernetes.io/component: client
    spec:
      containers:
      - name: client
        image: alpine
        envFrom:
        - configMapRef:
            name: clientv1config
        resources:
          limits:
            memory: "32Mi"
            cpu: "5m"
        command: [ "/bin/sh", "-c", "--" ]
        args:  [ "while true; do echo $(wget -qO- ${API_URL}) && sleep 5; done;" ]
---
apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: gag
  name: clientv2
spec:
  selector:
    matchLabels:
      app.kubernetes.io/part-of: gag-cs
      app.kubernetes.io/component: client
  template:
    metadata:
      labels:
        app.kubernetes.io/part-of: gag-cs
        app.kubernetes.io/component: client
    spec:
      containers:
      - name: client
        image: alpine
        envFrom:
        - configMapRef:
            name: clientv2config
        resources:
          limits:
            memory: "32Mi"
            cpu: "5m"
        command: [ "/bin/sh", "-c", "--" ]
        args:  [ "while true; do echo $(wget -qO- ${API_URL}) && sleep 5; done;" ]  
---
apiVersion: v1
kind: Service
metadata:
  namespace: gag
  name: apiv1
spec:
  selector:
    app.kubernetes.io/part-of: gag-cs
    app.kubernetes.io/component: api 
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: Service
metadata:
  namespace: gag
  name: apiv2
spec:
  selector:
    app.kubernetes.io/part-of: gag-cs
    app.kubernetes.io/component: api 
  ports:
  - port: 80
    targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clientv1config
  namespace: gag
data:
  API_URL: http://apiv1
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: clientv2config
  namespace: gag
data:
  API_URL: http://apiv2

